# Generated by Django 5.0.1 on 2024-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn13',
            field=models.BigIntegerField(null=True),
        ),
    ]
