# Generated by Django 5.0.1 on 2024-01-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0003_alter_books_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tester',
            fields=[
                ('checker', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
