# Generated by Django 5.0.1 on 2024-02-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0004_tester'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tester',
        ),
        migrations.AddIndex(
            model_name='shelves',
            index=models.Index(fields=['work_id'], name='engine_api__work_id_576611_idx'),
        ),
        migrations.AddIndex(
            model_name='shelves',
            index=models.Index(fields=['tag_name'], name='engine_api__tag_nam_89752b_idx'),
        ),
    ]
