# Generated by Django 5.0.1 on 2024-02-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0005_delete_tester_shelves_engine_api__work_id_576611_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildShelves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('counter', models.IntegerField()),
                ('tag_total_count', models.IntegerField()),
                ('tag_total_count_norm', models.FloatField()),
                ('tag_num_work', models.IntegerField()),
                ('work_total_count', models.IntegerField()),
                ('work_total_count_norm', models.FloatField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='shelves',
            name='engine_api__work_id_576611_idx',
        ),
        migrations.RemoveIndex(
            model_name='shelves',
            name='engine_api__tag_nam_89752b_idx',
        ),
    ]
