# Generated by Django 5.0.1 on 2024-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0006_buildshelves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildshelves',
            name='work_total_count_norm',
            field=models.FloatField(null=True),
        ),
    ]
