# Generated by Django 5.0.1 on 2024-02-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0007_alter_buildshelves_work_total_count_norm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildshelves',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
