# Generated by Django 5.0.1 on 2024-02-02 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0008_alter_buildshelves_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BuildShelves',
        ),
    ]
