# Generated by Django 5.0.1 on 2024-02-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_api', '0009_delete_buildshelves'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildWorks',
            fields=[
                ('book_id', models.IntegerField()),
                ('work_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(null=True)),
                ('title_without_series', models.TextField(null=True)),
                ('isbn', models.BigIntegerField(null=True)),
                ('isbn13', models.BigIntegerField(null=True)),
                ('text_reviews_count', models.IntegerField(null=True)),
                ('ratings_count', models.IntegerField(null=True)),
                ('average_rating', models.FloatField(null=True)),
                ('series', models.TextField(null=True)),
                ('country_code', models.TextField(null=True)),
                ('language_code', models.TextField(null=True)),
                ('asin', models.CharField(max_length=20, null=True)),
                ('kindle_asin', models.CharField(max_length=20, null=True)),
                ('is_ebook', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('num_pages', models.IntegerField(null=True)),
                ('publication_day', models.IntegerField(null=True)),
                ('publication_month', models.IntegerField(null=True)),
                ('publication_year', models.IntegerField(null=True)),
                ('format', models.TextField(null=True)),
                ('publisher', models.TextField(null=True)),
                ('edition_information', models.TextField(null=True)),
                ('similar_books', models.TextField(null=True)),
            ],
        ),
    ]
